package index

import (
	"testing"
)

func TestDetermineFileCategory(t *testing.T) {
	generatedContent := []byte("// Code generated by mockgen. DO NOT EDIT.\npackage mock")

	tests := []struct {
		name      string
		filename  string
		content   []byte
		want      FileCategory
		wantFlags fileRankFlags
	}{
		{
			name:      "test file",
			filename:  "foo_test.go",
			content:   []byte("package foo"),
			want:      FileCategoryTest,
			wantFlags: fileRankTest,
		},
		{
			name:      "vendor file",
			filename:  "vendor/foo.go",
			content:   []byte("package foo"),
			want:      FileCategoryVendored,
			wantFlags: fileRankVendored,
		},
		{
			name:      "generated file",
			filename:  "foo.go",
			content:   generatedContent,
			want:      FileCategoryGenerated,
			wantFlags: fileRankGenerated,
		},
		{
			name:      "generated test",
			filename:  "mock_test.go",
			content:   generatedContent,
			want:      FileCategoryTest,
			wantFlags: fileRankTest | fileRankGenerated,
		},
		{
			name:      "vendored test",
			filename:  "vendor/foo_test.go",
			content:   []byte("package foo"),
			want:      FileCategoryTest,
			wantFlags: fileRankTest | fileRankVendored,
		},
		{
			name:      "generated vendored file",
			filename:  "vendor/mock.go",
			content:   generatedContent,
			want:      FileCategoryVendored,
			wantFlags: fileRankVendored | fileRankGenerated,
		},
		{
			name:      "generated vendored test",
			filename:  "vendor/mock_test.go",
			content:   generatedContent,
			want:      FileCategoryTest,
			wantFlags: fileRankTest | fileRankVendored | fileRankGenerated,
		},
		{
			name:     "config file",
			filename: "package.json",
			content:  []byte("{}"),
			want:     FileCategoryConfig,
		},
		{
			name:      "dot file",
			filename:  ".gitignore",
			content:   []byte("*.o"),
			want:      FileCategoryDotFile,
			wantFlags: fileRankVendored,
		},
		{
			name:     "documentation file",
			filename: "README.md",
			content:  []byte("# Documentation"),
			want:     FileCategoryDocumentation,
		},
		{
			name:     "default file",
			filename: "main.go",
			content:  []byte("package main"),
			want:     FileCategoryDefault,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := &Document{
				Name:    tt.filename,
				Content: tt.content,
			}

			DetermineFileCategory(doc)
			if doc.Category != tt.want {
				t.Fatalf("category = %v, want %v", doc.Category, tt.want)
			}
			if got := doc.rankFlags; got != tt.wantFlags {
				t.Fatalf("rank flags = %03b, want %03b", got, tt.wantFlags)
			}
		})
	}
}

func TestDetermineFileCategorySkippedRankFlags(t *testing.T) {
	for _, tc := range []struct {
		skip      SkipReason
		generated bool
	}{
		{SkipReasonTooSmall, true},
		{SkipReasonTooManyTrigrams, true},
		{SkipReasonTooLarge, false},
		{SkipReasonBinary, false},
		{SkipReasonMissing, false},
	} {
		t.Run(tc.skip.explanation(), func(t *testing.T) {
			doc := Document{
				Name:       "vendor/mock_test.go",
				Content:    []byte("// Code generated by mockgen. DO NOT EDIT.\npackage mock"),
				SkipReason: tc.skip,
			}
			DetermineFileCategory(&doc)
			want := fileRankTest | fileRankVendored
			if tc.generated {
				want |= fileRankGenerated
			}
			if doc.rankFlags != want {
				t.Fatalf("rank flags = %03b, want %03b", doc.rankFlags, want)
			}
			wantCategory := FileCategoryTest
			if tc.skip == SkipReasonBinary {
				wantCategory = FileCategoryBinary
			}
			if doc.Category != wantCategory {
				t.Fatalf("category = %v, want %v", doc.Category, wantCategory)
			}
		})
	}
}
