package index

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/sourcegraph/zoekt"
)

func TestMergePreservesStoredCategoryForSkippedGeneratedFile(t *testing.T) {
	sb, err := NewShardBuilder(&zoekt.Repository{Name: "repo"})
	if err != nil {
		t.Fatalf("NewShardBuilder: %v", err)
	}

	err = sb.Add(Document{
		Name:       "generated.go",
		Content:    []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage generated\n"),
		SkipReason: SkipReasonTooManyTrigrams,
	})
	if err != nil {
		t.Fatalf("Add: %v", err)
	}

	tmpDir := t.TempDir()
	inputPath := filepath.Join(tmpDir, "input.zoekt")
	if err := builderWriteAll(inputPath, sb); err != nil {
		t.Fatalf("builderWriteAll: %v", err)
	}

	inputFile, err := os.Open(inputPath)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer inputFile.Close()

	indexFile, err := NewIndexFile(inputFile)
	if err != nil {
		t.Fatalf("NewIndexFile: %v", err)
	}
	defer indexFile.Close()

	tmpName, dstName, err := Merge(tmpDir, indexFile)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}
	if err := os.Rename(tmpName, dstName); err != nil {
		t.Fatalf("Rename: %v", err)
	}

	mergedFile, err := os.Open(dstName)
	if err != nil {
		t.Fatalf("Open merged shard: %v", err)
	}
	defer mergedFile.Close()

	mergedIndexFile, err := NewIndexFile(mergedFile)
	if err != nil {
		t.Fatalf("NewIndexFile merged shard: %v", err)
	}
	defer mergedIndexFile.Close()

	searcher, err := NewSearcher(mergedIndexFile)
	if err != nil {
		t.Fatalf("NewSearcher: %v", err)
	}
	defer searcher.Close()

	data := searcher.(*indexData)
	if got := data.getCategory(0); got != FileCategoryGenerated {
		t.Fatalf("got category %v, want %v", got, FileCategoryGenerated)
	}
}

// We compare 2 simple shards before and after the transformation
// explode(merge(shard1, shard2)). We expect the input and output shards to be
// identical.
func TestExplode(t *testing.T) {
	simpleShards := []string{
		".././testdata/shards/repo_v16.00000.zoekt",
		".././testdata/shards/repo2_v16.00000.zoekt",
	}

	// repo name -> IndexMetadata
	m := make(map[string]*zoekt.IndexMetadata, 2)

	// merge
	var files []IndexFile
	for _, fn := range simpleShards {
		f, err := os.Open(fn)
		if err != nil {
			t.Fatal(err)
		}
		defer f.Close()

		indexFile, err := NewIndexFile(f)
		if err != nil {
			t.Fatal(err)
		}
		defer indexFile.Close()

		// We save indexMeta because the fields ID and IndexTime are the 2 sources of
		// non-determinism when building a new shard.
		repoMeta, indexMeta, err := ReadMetadata(indexFile)
		if err != nil {
			t.Fatal(err)
		}
		if len(repoMeta) != 1 {
			t.Fatal("this test assumes that indexFile contains only 1 repo")
		}
		m[repoMeta[0].Name] = indexMeta

		files = append(files, indexFile)
	}

	tmpDir := t.TempDir()
	tmpName, dstName, err := Merge(tmpDir, files...)
	if err != nil {
		t.Fatal(err)
	}
	err = os.Rename(tmpName, dstName)
	if err != nil {
		t.Fatal(err)
	}

	// explode
	f, err := os.Open(dstName)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	indexFile, err := NewIndexFile(f)
	if err != nil {
		t.Fatal(err)
	}
	defer indexFile.Close()

	overwriteIndexTimeAndID := func(ib *ShardBuilder) {
		ib.ID = m[ib.repoList[0].Name].ID
		ib.IndexTime = m[ib.repoList[0].Name].IndexTime
	}
	exploded, err := explode(tmpDir, indexFile, overwriteIndexTimeAndID)
	if err != nil {
		t.Fatal(err)
	}
	for tmp, final := range exploded {
		err = os.Rename(tmp, final)
		if err != nil {
			t.Fatal(err)
		}
	}

	for _, s := range simpleShards {
		checkSameShards(t, s, filepath.Join(tmpDir, filepath.Base(s)))
	}
}

// checkSameShards compares 2 shards byte by byte. The shards are expected to be
// small enough to be read in all at once.
func checkSameShards(t *testing.T, shard1, shard2 string) {
	t.Helper()
	b1, err := os.ReadFile(shard1)
	if err != nil {
		t.Fatal(err)
	}

	b2, err := os.ReadFile(shard2)
	if err != nil {
		t.Fatal(err)
	}

	// We could also use bytes.Equal, but the output of cmd.Diff is very helpful for
	// differences in metadata.
	d := cmp.Diff(b1, b2)
	if d == "" {
		return
	}

	if *update {
		t.Logf("updating %s", shard1)
		err := os.WriteFile(shard1, b2, 0o600)
		if err != nil {
			t.Fatal(err)
		}
		return
	}

	t.Fatalf("-%s\n+%s:\n%s", shard1, shard2, d)
}
