package index

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/sourcegraph/zoekt"
)

func TestMergePreservesStoredCategoryForSkippedGeneratedFile(t *testing.T) {
	sb, err := NewShardBuilder(&zoekt.Repository{Name: "repo"})
	if err != nil {
		t.Fatalf("NewShardBuilder: %v", err)
	}

	err = sb.Add(Document{
		Name:       "generated.go",
		Content:    []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage generated\n"),
		SkipReason: SkipReasonTooManyTrigrams,
	})
	if err != nil {
		t.Fatalf("Add: %v", err)
	}

	tmpDir := t.TempDir()
	inputPath := filepath.Join(tmpDir, "input.zoekt")
	if err := builderWriteAll(inputPath, sb); err != nil {
		t.Fatalf("builderWriteAll: %v", err)
	}

	inputFile, err := os.Open(inputPath)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer inputFile.Close()

	indexFile, err := NewIndexFile(inputFile)
	if err != nil {
		t.Fatalf("NewIndexFile: %v", err)
	}
	defer indexFile.Close()

	result, err := Merge(tmpDir, indexFile)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}
	if !result.HasOutput() {
		t.Fatal("Merge produced no output")
	}
	if err := os.Rename(result.TempPath, result.FinalPath); err != nil {
		t.Fatalf("Rename: %v", err)
	}

	mergedFile, err := os.Open(result.FinalPath)
	if err != nil {
		t.Fatalf("Open merged shard: %v", err)
	}
	defer mergedFile.Close()

	mergedIndexFile, err := NewIndexFile(mergedFile)
	if err != nil {
		t.Fatalf("NewIndexFile merged shard: %v", err)
	}
	defer mergedIndexFile.Close()

	searcher, err := NewSearcher(mergedIndexFile)
	if err != nil {
		t.Fatalf("NewSearcher: %v", err)
	}
	defer searcher.Close()

	data := searcher.(*indexData)
	if got := data.getCategory(0); got != FileCategoryGenerated {
		t.Fatalf("got category %v, want %v", got, FileCategoryGenerated)
	}
}

// We compare 2 simple shards before and after the transformation
// explode(merge(shard1, shard2)). We expect the input and output shards to be
// identical.
func TestExplode(t *testing.T) {
	simpleShards := []string{
		".././testdata/shards/repo_v16.00000.zoekt",
		".././testdata/shards/repo2_v16.00000.zoekt",
	}

	// repo name -> IndexMetadata
	m := make(map[string]*zoekt.IndexMetadata, 2)

	// merge
	var files []IndexFile
	for _, fn := range simpleShards {
		f, err := os.Open(fn)
		if err != nil {
			t.Fatal(err)
		}
		defer f.Close()

		indexFile, err := NewIndexFile(f)
		if err != nil {
			t.Fatal(err)
		}
		defer indexFile.Close()

		// We save indexMeta because the fields ID and IndexTime are the 2 sources of
		// non-determinism when building a new shard.
		repoMeta, indexMeta, err := ReadMetadata(indexFile)
		if err != nil {
			t.Fatal(err)
		}
		if len(repoMeta) != 1 {
			t.Fatal("this test assumes that indexFile contains only 1 repo")
		}
		m[repoMeta[0].Name] = indexMeta

		files = append(files, indexFile)
	}

	tmpDir := t.TempDir()
	result, err := Merge(tmpDir, files...)
	if err != nil {
		t.Fatal(err)
	}
	if !result.HasOutput() {
		t.Fatal("Merge produced no output")
	}
	err = os.Rename(result.TempPath, result.FinalPath)
	if err != nil {
		t.Fatal(err)
	}

	// explode
	f, err := os.Open(result.FinalPath)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	indexFile, err := NewIndexFile(f)
	if err != nil {
		t.Fatal(err)
	}
	defer indexFile.Close()

	overwriteIndexTimeAndID := func(ib *ShardBuilder) {
		ib.ID = m[ib.repoList[0].Name].ID
		ib.IndexTime = m[ib.repoList[0].Name].IndexTime
	}
	exploded, err := explode(tmpDir, indexFile, overwriteIndexTimeAndID)
	if err != nil {
		t.Fatal(err)
	}
	for tmp, final := range exploded {
		err = os.Rename(tmp, final)
		if err != nil {
			t.Fatal(err)
		}
	}

	for _, s := range simpleShards {
		checkSameShards(t, s, filepath.Join(tmpDir, filepath.Base(s)))
	}
}

func TestMergeAllTombstonedProducesNoShard(t *testing.T) {
	dir := t.TempDir()
	sb := newShardBuilder(0)
	sb.indexFormatVersion = NextIndexFormatVersion
	if err := sb.setRepository(&zoekt.Repository{ID: 1, Name: "deleted", Tombstone: true}); err != nil {
		t.Fatal(err)
	}
	if err := sb.Add(Document{Name: "f", Content: []byte("content")}); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(dir, "all-tombstoned.zoekt")
	if err := builderWriteAll(path, sb); err != nil {
		t.Fatal(err)
	}
	f, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	indexFile, err := NewIndexFile(f)
	if err != nil {
		t.Fatal(err)
	}
	defer indexFile.Close()

	result, err := Merge(dir, indexFile)
	if err != nil {
		t.Fatal(err)
	}
	if result.HasOutput() {
		t.Fatalf("Merge produced an output for an all-tombstoned shard: %+v", result)
	}
	if matches, err := filepath.Glob(filepath.Join(dir, "compound-*")); err != nil {
		t.Fatal(err)
	} else if len(matches) != 0 {
		t.Fatalf("Merge wrote compound shards: %v", matches)
	}
}

func TestShardBuilderRejectsRepositorylessShard(t *testing.T) {
	sb := newShardBuilder(0)
	sb.indexFormatVersion = NextIndexFormatVersion
	if err := sb.Write(&bytes.Buffer{}); err == nil {
		t.Fatal("Write succeeded without repository metadata")
	}
}

func TestVerifyRepositoryReferences(t *testing.T) {
	tests := []struct {
		name      string
		data      indexData
		wantError bool
	}{
		{
			name: "valid",
			data: indexData{
				repoMetaData:    make([]zoekt.Repository, 2),
				fileBranchMasks: make([]uint64, 3),
				repos:           []uint16{0, 0, 1},
			},
		},
		{
			name: "wrong reference count",
			data: indexData{
				repoMetaData:    make([]zoekt.Repository, 1),
				fileBranchMasks: make([]uint64, 2),
				repos:           []uint16{0},
			},
			wantError: true,
		},
		{
			name: "repository out of range",
			data: indexData{
				repoMetaData:    make([]zoekt.Repository, 1),
				fileBranchMasks: make([]uint64, 1),
				repos:           []uint16{1},
			},
			wantError: true,
		},
		{
			name: "repositories out of order",
			data: indexData{
				repoMetaData:    make([]zoekt.Repository, 2),
				fileBranchMasks: make([]uint64, 2),
				repos:           []uint16{1, 0},
			},
			wantError: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.data.verifyRepositoryReferences()
			if (err != nil) != tt.wantError {
				t.Fatalf("verifyRepositoryReferences() error = %v, wantError %t", err, tt.wantError)
			}
		})
	}
}

func TestMergeAndExplodePreserveRepositoryWithoutDocuments(t *testing.T) {
	dir := t.TempDir()
	sb := newShardBuilder(0)
	sb.indexFormatVersion = NextIndexFormatVersion
	if err := sb.setRepository(&zoekt.Repository{ID: 1, Name: "deleted", Tombstone: true}); err != nil {
		t.Fatal(err)
	}
	if err := sb.Add(Document{Name: "f", Content: []byte("content")}); err != nil {
		t.Fatal(err)
	}
	if err := sb.setRepository(&zoekt.Repository{ID: 2, Name: "empty"}); err != nil {
		t.Fatal(err)
	}

	inputPath := filepath.Join(dir, "input.zoekt")
	if err := builderWriteAll(inputPath, sb); err != nil {
		t.Fatal(err)
	}
	f, err := os.Open(inputPath)
	if err != nil {
		t.Fatal(err)
	}
	indexFile, err := NewIndexFile(f)
	if err != nil {
		t.Fatal(err)
	}

	result, err := Merge(dir, indexFile)
	indexFile.Close()
	if err != nil {
		t.Fatal(err)
	}
	if !result.HasOutput() {
		t.Fatal("Merge produced no output for a live repository without documents")
	}
	if err := os.Rename(result.TempPath, result.FinalPath); err != nil {
		t.Fatal(err)
	}

	repos, _, err := ReadMetadataPath(result.FinalPath)
	if err != nil {
		t.Fatal(err)
	}
	if len(repos) != 1 || repos[0].Name != "empty" {
		t.Fatalf("merged repositories = %v, want empty", repos)
	}

	if err := Explode(dir, result.FinalPath); err != nil {
		t.Fatal(err)
	}
	opts := Options{
		IndexDir:              dir,
		RepositoryDescription: *repos[0],
	}
	simplePath := opts.shardNameVersion(IndexFormatVersion, 0)
	repos, _, err = ReadMetadataPath(simplePath)
	if err != nil {
		t.Fatal(err)
	}
	if len(repos) != 1 || repos[0].Name != "empty" {
		t.Fatalf("exploded repositories = %v, want empty", repos)
	}
}

// TestExplodeEmptyShard verifies that exploding a compound shard with zero
// repositories removes the shard and returns success, instead of failing and
// leaving an unusable shard on disk. A compound shard reaches this state once
// all of its repos have been tombstoned and merged out. Such a shard cannot be
// loaded by zoekt-webserver, so leaving it in place drives up the indexed
// search error rate until it is removed.
func TestExplodeEmptyShard(t *testing.T) {
	dir := t.TempDir()

	path := filepath.Join(dir, fmt.Sprintf("compound-empty_v%d.00000.zoekt", NextIndexFormatVersion))
	writeLegacyRepositorylessShard(t, path)

	// Confirm the shard really is the empty-shard case.
	if _, _, err := ReadMetadataPath(path); !errors.Is(err, ErrEmptyShard) {
		t.Fatalf("ReadMetadataPath: got %v, want ErrEmptyShard", err)
	}

	// Explode should remove the empty shard and return nil.
	if err := Explode(dir, path); err != nil {
		t.Fatalf("Explode: %v", err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("empty shard was not removed, stat err = %v", err)
	}
}

func writeLegacyRepositorylessShard(t *testing.T, path string) {
	t.Helper()

	sb := newShardBuilder(0)
	sb.indexFormatVersion = NextIndexFormatVersion
	sb.ID = "legacy-shard-id"
	if err := sb.setRepository(&zoekt.Repository{ID: 1, Name: "legacy"}); err != nil {
		t.Fatal(err)
	}
	if err := builderWriteAll(path, sb); err != nil {
		t.Fatalf("builderWriteAll: %v", err)
	}

	f, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	indexFile, err := NewIndexFile(f)
	if err != nil {
		t.Fatal(err)
	}
	var toc indexTOC
	if err := (&reader{r: indexFile}).readTOCSections(&toc, []string{"repoMetaData"}); err != nil {
		indexFile.Close()
		t.Fatal(err)
	}
	indexFile.Close()

	emptyMetadata := bytes.Repeat([]byte(" "), int(toc.repoMetaData.sz))
	copy(emptyMetadata, "[]")
	f, err = os.OpenFile(path, os.O_WRONLY, 0)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	if _, err := f.WriteAt(emptyMetadata, int64(toc.repoMetaData.off)); err != nil {
		t.Fatal(err)
	}
}

// checkSameShards compares 2 shards byte by byte. The shards are expected to be
// small enough to be read in all at once.
func checkSameShards(t *testing.T, shard1, shard2 string) {
	t.Helper()
	b1, err := os.ReadFile(shard1)
	if err != nil {
		t.Fatal(err)
	}

	b2, err := os.ReadFile(shard2)
	if err != nil {
		t.Fatal(err)
	}

	// We could also use bytes.Equal, but the output of cmd.Diff is very helpful for
	// differences in metadata.
	d := cmp.Diff(b1, b2)
	if d == "" {
		return
	}

	if *update {
		t.Logf("updating %s", shard1)
		err := os.WriteFile(shard1, b2, 0o600)
		if err != nil {
			t.Fatal(err)
		}
		return
	}

	t.Fatalf("-%s\n+%s:\n%s", shard1, shard2, d)
}
