package index

import (
	"strings"
	"testing"

	"github.com/sourcegraph/zoekt"
)

func TestShardName(t *testing.T) {
	tests := []struct {
		name     string
		indexDir string
		prefix   string
		version  int
		shardNum int
		expected string
	}{
		{
			name:     "short prefix",
			indexDir: "index",
			prefix:   "short",
			version:  1,
			shardNum: 42,
			expected: "index/short_v1.00042.zoekt",
		},
		{
			name:     "long prefix truncated",
			indexDir: "index",
			prefix:   strings.Repeat("a", 300),
			version:  2,
			shardNum: 1,
			expected: "index/" + strings.Repeat("a", 200) + "003ef1ba" + "_v2.00001.zoekt",
		},
		{
			name:     "empty indexDir",
			prefix:   "short",
			version:  1,
			expected: "short_v1.00000.zoekt",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			actual := shardName(test.indexDir, test.prefix, test.version, test.shardNum)
			if actual != test.expected {
				t.Errorf("expected %q, got %q", test.expected, actual)
			}
		})
	}
}

func TestDetermineLanguageIfUnknown(t *testing.T) {
	tests := []struct {
		name        string
		doc         Document
		wantLang    string
		skipContent bool
	}{
		{
			name: "already has language",
			doc: Document{
				Name:     "test.java",
				Language: "Go",
				Content:  []byte("package main"),
			},
			wantLang: "Go",
		},
		{
			name: "skipped file",
			doc: Document{
				Name:       "large.js",
				SkipReason: SkipReasonTooLarge,
				Content:    []byte(notIndexedMarker + "too large"),
			},
			wantLang: "JavaScript",
		},
		{
			name: "skipped file with unknown extension",
			doc: Document{
				Name:       "deadb33f",
				SkipReason: SkipReasonBinary,
				Content:    []byte(notIndexedMarker + "binary"),
			},
			wantLang: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			DetermineLanguageIfUnknown(&tt.doc)
			if tt.doc.Language != tt.wantLang {
				t.Errorf("DetermineLanguageIfUnknown() got language = %v, want %v", tt.doc.Language, tt.wantLang)
			}
		})
	}
}

func TestShardBuilderAddDeterminesCategoryBeforeReplacingSkippedContent(t *testing.T) {
	b, err := NewShardBuilder(&zoekt.Repository{})
	if err != nil {
		t.Fatalf("NewShardBuilder: %v", err)
	}

	err = b.Add(Document{
		Name:       "generated.go",
		Content:    []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage generated\n"),
		SkipReason: SkipReasonTooManyTrigrams,
	})
	if err != nil {
		t.Fatalf("Add: %v", err)
	}

	if len(b.categories) != 1 {
		t.Fatalf("got %d categories, want 1", len(b.categories))
	}

	category, err := decodeCategory(b.categories[0])
	if err != nil {
		t.Fatalf("decodeCategory: %v", err)
	}
	if category != FileCategoryGenerated {
		t.Fatalf("got category %v, want %v", category, FileCategoryGenerated)
	}

	if len(b.languages) != 2 {
		t.Fatalf("got %d encoded language bytes, want 2", len(b.languages))
	}

	langCode := uint16(b.languages[0]) | uint16(b.languages[1])<<8
	got, ok := b.languageMap["Go"]
	if !ok {
		t.Fatalf("languageMap missing Go entry: %#v", b.languageMap)
	}
	if got != langCode {
		t.Fatalf("got stored language code %d, want Go=%d", langCode, got)
	}
}
